<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="65259" started-at="2019-10-27T11:30:01Z" finished-at="2019-10-27T11:31:06Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="65259" started-at="2019-10-27T11:30:01Z" finished-at="2019-10-27T11:31:06Z">
      <class name="com.amazon.test.LoginTest">
        <test-method status="PASS" signature="Before()[pri:0, instance:com.amazon.test.LoginTest@721e0f4f]" name="Before" is-config="true" duration-ms="49146" started-at="2019-10-27T17:00:01Z" finished-at="2019-10-27T17:00:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Before -->
        <test-method status="FAIL" signature="LoginLogo()[pri:0, instance:com.amazon.test.LoginTest@721e0f4f]" name="LoginLogo" duration-ms="33" started-at="2019-10-27T17:00:50Z" finished-at="2019-10-27T17:00:50Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.amazon.pages.LoginPage.validateLogo(LoginPage.java:46)
	at com.amazon.test.LoginTest.LoginLogo(LoginTest.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:663)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:849)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1157)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginLogo -->
        <test-method status="PASS" signature="After()[pri:0, instance:com.amazon.test.LoginTest@721e0f4f]" name="After" is-config="true" duration-ms="975" started-at="2019-10-27T17:00:50Z" finished-at="2019-10-27T17:00:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- After -->
        <test-method status="PASS" signature="Before()[pri:0, instance:com.amazon.test.LoginTest@721e0f4f]" name="Before" is-config="true" duration-ms="7999" started-at="2019-10-27T17:00:51Z" finished-at="2019-10-27T17:00:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Before -->
        <test-method status="FAIL" signature="LoginPageTitle()[pri:0, instance:com.amazon.test.LoginTest@721e0f4f]" name="LoginPageTitle" duration-ms="7" started-at="2019-10-27T17:00:59Z" finished-at="2019-10-27T17:00:59Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Online Shopping site in India: Shop Online for Mobiles, Books, Watches, Shoes and More - Amazon.in] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Online Shopping site in India: Shop Online for Mobiles, Books, Watches, Shoes and More - Amazon.in] but found []
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at com.amazon.test.LoginTest.LoginPageTitle(LoginTest.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:663)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:849)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1157)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginPageTitle -->
        <test-method status="PASS" signature="After()[pri:0, instance:com.amazon.test.LoginTest@721e0f4f]" name="After" is-config="true" duration-ms="93" started-at="2019-10-27T17:00:59Z" finished-at="2019-10-27T17:00:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- After -->
        <test-method status="PASS" signature="Before()[pri:0, instance:com.amazon.test.LoginTest@721e0f4f]" name="Before" is-config="true" duration-ms="6914" started-at="2019-10-27T17:00:59Z" finished-at="2019-10-27T17:01:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Before -->
        <test-method status="FAIL" signature="LoginSearch()[pri:0, instance:com.amazon.test.LoginTest@721e0f4f]" name="LoginSearch" duration-ms="2" started-at="2019-10-27T17:01:06Z" finished-at="2019-10-27T17:01:06Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.amazon.pages.LoginPage.enterItem(LoginPage.java:51)
	at com.amazon.test.LoginTest.LoginSearch(LoginTest.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:663)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:849)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1157)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginSearch -->
        <test-method status="PASS" signature="After()[pri:0, instance:com.amazon.test.LoginTest@721e0f4f]" name="After" is-config="true" duration-ms="44" started-at="2019-10-27T17:01:06Z" finished-at="2019-10-27T17:01:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- After -->
      </class> <!-- com.amazon.test.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
